# Listas

La primera estructura de datos que veremos son las **listas**. Éstas son un conjunto de elementos ordenados separados por comas y escritos entre claudators, `[]`. 

Las listas son:
- hetereogéneas: los elementos pueden ser de distinto tipo en una misma lista
- mutables: los elementos pueden ser modificados

Un ejemplo de lista sería

In [1]:
l1 = ["Juan", 31, 175.5, True]
print(l1)
print(type(l1))

['Juan', 31, 175.5, True]
<class 'list'>


Acceder a sus elementos, es muy fácil.

In [7]:
l1[1]

31

In [3]:
l1[2:4]

[175.5, True]

In [4]:
l1[:3]

['Juan', 31, 175.5]

In [6]:
l1[2:]

[175.5, True]

In [8]:
# Longitu de la lista
len(l1)

4

Podemos modificar elementos de una lista.

In [10]:
nombres = ["Ana", "Luisa", "Jorge", "Renzo"]
nombres

['Ana', 'Luisa', 'Jorge', 'Renzo']

In [11]:
nombres[1] = "Camila"
nombres

['Ana', 'Camila', 'Jorge', 'Renzo']

**El método `append`**

In [12]:
nombres2 = ["Carol", "Karina", "Andrés"]
nombres.append(nombres2)
nombres

['Ana', 'Camila', 'Jorge', 'Renzo', ['Carol', 'Karina', 'Andrés']]

In [13]:
nombres.append("Mario")
nombres

['Ana', 'Camila', 'Jorge', 'Renzo', ['Carol', 'Karina', 'Andrés'], 'Mario']

**Observación.** Los elementos añadidos con el método `.append()`, se incluyen al final.

Si quisiéramos añadir un nuevo elemento a una lista, pero no lo quisiéramos al final, sino en una posición específica, entonces utilizaremos el método `.insert()` al que primero le indicamos el índice donde queremos posicionar el nuevo elemento y, en segundo lugar, indicamos dicho nuevo elemento.

In [14]:
# Queremos añadir el nombre "Rocio" en la 2da posicion
nombres

['Ana', 'Camila', 'Jorge', 'Renzo', ['Carol', 'Karina', 'Andrés'], 'Mario']

In [15]:
nombres.insert(1,"Rocío")
nombres

['Ana',
 'Rocío',
 'Camila',
 'Jorge',
 'Renzo',
 ['Carol', 'Karina', 'Andrés'],
 'Mario']

In [17]:
# Practicando
names = ["Mario", "Cristian", "Juan"]
print(names)

names.insert(1, "Andrés")
print(names)
names.insert(3, "Miguel")
print(names)

['Mario', 'Cristian', 'Juan']
['Mario', 'Andrés', 'Cristian', 'Juan']
['Mario', 'Andrés', 'Cristian', 'Miguel', 'Juan']


**Ejercicio**

- Vamos a pedirle al usuario la longitud de una lista y haremos que introduzca por teclado tantos números enteros como haya indicado, que se guardarán en una lista. Al acabar, imprimiremos la lista.

In [20]:
count = int(input("Número de elementos de la lista : "))

lista = []
for i in range(0,count):
    lista.append(int(input("Ingrese elemento : ")))

lista    

Número de elementos de la lista : 3
Ingrese elemento : 12
Ingrese elemento : 15
Ingrese elemento : 9


[12, 15, 9]

## Bucles en listas

In [1]:
nombres = ["Ana","Luis","Jorge","Leonel","Gabriela"]

In [4]:
# i como índice o posición
for i in range(0,len(nombres)):
    print(nombres[i])

Ana
Luis
Jorge
Leonel
Gabriela


In [5]:
# j de item, j de elemento de una colección
for j in nombres:
    print(j)

Ana
Luis
Jorge
Leonel
Gabriela


## Concatenación de listas
Dadas dos o más listas, podemos concatenarlas haciendo uso de la función `+`

In [6]:
l1 = [True, 21, "Marta"]
l2 = [22.5, False, 22, "Rafa"]
print(l1 + l2)

[True, 21, 'Marta', 22.5, False, 22, 'Rafa']


## Repetición de listas

Podemos repetir una misma lista tantas veces como queramos con la función `*`

In [7]:
abc = ["A", "B", "C"]
print(abc * 5)

['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C']


In [11]:
["Python"]*10

['Python',
 'Python',
 'Python',
 'Python',
 'Python',
 'Python',
 'Python',
 'Python',
 'Python',
 'Python']

## Lista vacía

In [14]:
empty_list = []
len(empty_list)

0

## Listas anidadas

Las listas anidadas son listas dentro de listas. Es decir, las listas no solo pueden contener números, strings o datos booleanos, sino que también pueden contener otras listas.



In [15]:
l = [["María", "Santos", "Fernández"],
     ["Juan", [1, 2, 3, 4, 5], 32], 
     2]
print(l)

[['María', 'Santos', 'Fernández'], ['Juan', [1, 2, 3, 4, 5], 32], 2]


Para acceder a un elemento, necesitamos indicar su índice. Si un elemento está en una lista dentro de una lista dentro de una lista, en primer lugar indicamos el índice de la lista exterior dentro de `[]`; después, el índice de la siguiente lista más exterior también entre `[]`; y por último, el índice de la lista más interna, claramente también entre `[]`.

Accedamos al string `Fernández`y luego al número `5`.

In [16]:
print(l[0][2]) # Fernández
print(l[1][1][4]) # 5

Fernández
5


## Más métodos de listas

El método `.count()` recibe un elemento como argumento y cuenta la cantidad de veces que aparece en la lista

In [17]:
lista1 = [2,3,0,1,2,0,6,0]
lista1.count(0)

3

In [24]:
numeros = [2,0,1,1,9,0,6,0]
counted = []
for element in numeros:
    if element not in counted:
        counted.append(element)
        if numeros.count(element) == 1:
            print("el numero {} aparece {} vez".format(element,numeros.count(element)))
        else:
            print("el numero {} aparece {} veces".format(element,numeros.count(element)))


el numero 2 aparece 1 vez
el numero 0 aparece 3 veces
el numero 1 aparece 2 veces
el numero 9 aparece 1 vez
el numero 6 aparece 1 vez


El método `.extend()` extiende la lista agregando al final el iterable indicado por parámetro.

In [25]:
numbers = [1, 2, 3, 4, 5]
print(numbers)
numbers.extend([6])
print(numbers)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


In [26]:
numbers.extend([7, 8])
print(numbers)
numbers.extend(range(9, 16))
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


**Observación.** Un iterable es un objeto de `Python` capaz de devolver sus elementos uno por uno, permitiendo ser iterado en un bucle for. De momento solo conocemos las listas y el resultado de `range()`, pero en secciones futuras veremos los diccionarios, las tuplas y los conjuntos, que también son objetos iterables.

El método `index()` recibe un elemento como argumento y devuelve el índice de la primera aparición en la lista.

In [36]:
numbers = [0, 1, 1, 2, 2, 2, 3, 4, 3, 4]
print(numbers.index(2))
print(numbers.index(4)) 

3
7


In [37]:
apellidos = ["Perez","Ruiz","Ramires","Tapia","Catillo"]
apellidos.index("Ramires")

2

El método `.pop()` devuelve el último elemento de la lista y lo borra de la misma.

In [39]:
print(numbers)
print(numbers.pop())
print(numbers)

[0, 1, 1, 2, 2, 2, 3, 4, 3, 4]
4
[0, 1, 1, 2, 2, 2, 3, 4, 3]


El método `.remove()` recibe como argumento un elemento y borra su primera aparición de la lista.

In [40]:
numbers = [0, 1, 2, 4, 3, 4, 5, 6, 7]
print(numbers)
numbers.remove(4)
print(numbers)

[0, 1, 2, 4, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7]


El método `.reverse()` devuelve la lista en orden inverso.

In [44]:
numbers = [1, -1, 2, -2, 3, -3]
numbers.reverse()
print(numbers)

[-3, 3, -2, 2, -1, 1]


El método `.sort()` devuelve la lista en orden. 

In [46]:
numbers = [1, 3, 5, 2, 4]
numbers.sort()
numbers

[1, 2, 3, 4, 5]

Si quisiésemos ordenar los elementos en orden decreciente, podríamos hacer uso del parámetro `reverse` del método `.sort()`:

In [47]:
numbers = [1, 3, 5, 2, 4]
numbers.sort(reverse = True)
print(numbers)

[5, 4, 3, 2, 1]


**Ejercicio**

- Dada una lista de nombres, le pediremos al usuario qué elemento quiere eliminar y lo eliminaremos de la lista.

In [57]:
lista1 = ["Juan","Romeo","Julieta","Marina","Luz","Jose"]
print(lista1)
print("Elemntos de la lista : ")
for i in range(0,len(lista1)):
    print("El elemento {} es {}.".format(i+1,lista1[i]))
print("*"*50)
print("Indique que elemento quiere eliminar")
indx = int(input("Escriba un número : "))
element = lista1[indx-1]
lista1.remove(element)
print(lista1)

['Juan', 'Romeo', 'Julieta', 'Marina', 'Luz', 'Jose']
Elemntos de la lista : 
El elemento 1 es Juan.
El elemento 2 es Romeo.
El elemento 3 es Julieta.
El elemento 4 es Marina.
El elemento 5 es Luz.
El elemento 6 es Jose.
**************************************************
Indique que elemento quiere eliminar
Escriba un número : 3
['Juan', 'Romeo', 'Marina', 'Luz', 'Jose']


In [58]:
l = ["m", "a", "r", "j", "b", "g", "i", "s", "f", "g"]
print("Esta es la lista original:", l)
c = input("Introduce el elemento que quieres eliminar ")

for e in l:
    if e == c:
        l.remove(e)

print("Esta es la lista actualizada", l)

Esta es la lista original: ['m', 'a', 'r', 'j', 'b', 'g', 'i', 's', 'f', 'g']
Introduce el elemento que quieres eliminar a
Esta es la lista actualizada ['m', 'r', 'j', 'b', 'g', 'i', 's', 'f', 'g']


**Ejercicio**

- Vamos a pedir al usuario que ingrese 5 números, los guardaremos en una lista y mostraremos la lista ordenada, siendo el usuario quien indique el orden: ascendente o descendente.

In [64]:
print("Ingreso de números")
nums = []
for i in range(0,5):
    nums.append(int(input("Ingresa un número entero : ")))
print("*"*50)
print("Odenaremos los elementos de la lista")
print("1. Orden ascendente\n2. Orden descendente\nIngrese un número")
n = int(input("Número : "))

while n != 1 and n != 2:
    n = int(input("Número : "))
if n == 1:
    nums.sort(reverse=False)
else:
    nums.sort(reverse=True)
print(nums)

Ingreso de números
Ingresa un número entero : 2
Ingresa un número entero : 4
Ingresa un número entero : 5
Ingresa un número entero : 7
Ingresa un número entero : 1
**************************************************
Odenaremos los elementos de la lista
1. Orden ascendente
2. Orden descendente
Ingrese un número
Número : 2
[7, 5, 4, 2, 1]


## Conversión a listas

Para convertir un objeto iterable de `Python` a lista, hay que usar la función `list()`

In [65]:
print(range(0, 100, 10))

range(0, 100, 10)


In [66]:
print(list(range(0, 100, 10)))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [67]:
print(type(list(range(0, 100, 10))))

<class 'list'>


**Ejercicio**

- Vamos a convertir los números impares del 0 al 30 a una lista y mostrar los elementos con el fomato "El valor {} ocupa el índice {}"

In [77]:
for i in range(0,30,2): 
    print("El {} ocupa la poscion {}.".format(i+1,int(i/2)+1))

El 1 ocupa la poscion 1.
El 3 ocupa la poscion 2.
El 5 ocupa la poscion 3.
El 7 ocupa la poscion 4.
El 9 ocupa la poscion 5.
El 11 ocupa la poscion 6.
El 13 ocupa la poscion 7.
El 15 ocupa la poscion 8.
El 17 ocupa la poscion 9.
El 19 ocupa la poscion 10.
El 21 ocupa la poscion 11.
El 23 ocupa la poscion 12.
El 25 ocupa la poscion 13.
El 27 ocupa la poscion 14.
El 29 ocupa la poscion 15.


## Matrices con listas

In [10]:
matriz = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

escrita en forma de tabla sería: `matrix` $= \displaystyle\begin{pmatrix} 1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9\\ 10 & 11 & 12\end{pmatrix}$

Para acceder a los elementos de una matriz en `Python`, utilizamos la sintaxis `[][]`, donde primero indicamos la fila y, a continuación, la columna

In [13]:
matriz[0][1]

2

In [15]:
# La 2da fila 
for j in range(0,len(matriz[0])):
    print(matriz[1][j])

4
5
6


In [16]:
# La 2da columna
for i in range(0,len(matriz)):
    print(matriz[i][1])

2
5
8
11


Podemos mostrar una matriz de `Python` en forma de tabla con un bucle `for`, del siguiente modo

In [17]:
for row in matriz:
    print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[10, 11, 12]


Si lo que queremos es mostrar todos los elementos de la matriz en columna, podemos utilizar dos bucles `for` anidados del siguiente modo:

In [18]:
for row in matriz:
    for element in row:
        print(element)

1
2
3
4
5
6
7
8
9
10
11
12


Si lo que queremos es mostrar la matriz en forma de tabla, sin comas ni claudators por en medio, lo podemos hacer de dos formas:

- Haciendo uso de las dimensiones de la matriz y, por tanto, de la función `range()`
- Sin hacer uso de las dimensiones

La primera forma sería:

In [28]:
# m es el número de filas y n, el de columnas
m = len(matriz)
n = len(matriz[0])

for i in range(0,m):
    for j in range(0,n):
        print(matriz[i][j], end = "   ")
    print("-")
    

1   2   3   -
4   5   6   -
7   8   9   -
10   11   12   -


**Observación.**

1. Como todas las filas tienen el mismo número de elementos, nos da igual si calculamos $n$ con la primera fila o con cualquier otra.
2. Hemos hecho uso del parámetro `end` de la función `print()` para indicar si, en vez de un salto de línea como ocurre por defecto, queremos que suceda otra cosa inmediatamente después de ejecutar la función `print()`. En este caso, hemos indicado que queremos un espacio en blanco.

Y la segunda forma, es la siguiente:

In [31]:
for row in matriz:
    for element in row:
        print(element, end = " ")
    print("*", end = " ")

1 2 3 * 4 5 6 * 7 8 9 * 10 11 12 * 

### Suma de matrices

Para poder sumar dos matrices, necesitamos que tengan la misma dimensión. Entonces, dadas $A$ y $B$ dos matrices con dimensión $m\times n$, su suma será una matriz de dimensión $m\times n$ y sus elementos se obtienen del siguiente modo:

$$\begin{array}{lll}A + B &=& (a_{ij})_{m\times n} + (b_{ij})_{m\times n} = (a_{ij} + b_{ij})_{m\times n}\\ 
&=&\begin{pmatrix} 
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\\
\end{pmatrix} + \begin{pmatrix} 
b_{11} &b_{12} & \cdots &b_{1n}\\
b_{21} &b_{22} & \cdots &b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
b_{m1} &b_{m2} & \cdots & b_{mn}\\
\end{pmatrix} = \begin{pmatrix} 
a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n}\\
a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn}\\
\end{pmatrix}
\end{array}$$

In [59]:
# Definiendo 2 matrices
A = [[1, 0, -3], [2, 0, 1], [-1, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3]]

In [60]:
# Sumando ambas matrices

if len(A) == len(B) and len(A[0]) == len(B[0]):
    C = []
    
    for i in range(len(A)):
        C.append([])
        for j in range(len(A[0])):
            C[i].append(A[i][j] + B[i][j])
else:
    print("No se pueden sumar ambas matrices")
C

[[0, -2, -3], [0, 3, 1], [-1, -1, -3]]

El resultado de sumar las matrices $A$ y $B$ ha sido

$$\begin{pmatrix}
1 & 0 & -3\\
2 & 0 & 1\\
-1 & -1 & 0\end{pmatrix} + \begin{pmatrix}
-1 & -2 & 0\\
-2 & -3 & 0\\
0 & 0 & -3\end{pmatrix} = 
\begin{pmatrix}
0 & -2 & -3\\
0 & -3 & 1\\
-1 & -1 & -3\end{pmatrix}$$

### Producto de matrices

Para poder multiplicar matrices, necesitamos que la matriz de la izquierda tenga el mismo número de columnas que número de filas tiene la matriz de la derecha. Entonces, dadas las matrices $A$ y $B$ de dimensiones $m\times n$ y $n\times p$ respectivamente, su producto será una matriz de dimensión $m\times p$ y se obtiene del siguiente modo:

$$\begin{array}{lll}A\cdot B &=& (a_{ij})_{m\times n}\cdot (b_{ij})_{n\times p} = \left(\sum_{k = 1}^n a_{ik}\cdot b_{kj}\right)_{m\times p}\\
&=& \begin{pmatrix} 
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\\
\end{pmatrix} \cdot \begin{pmatrix} 
b_{11} &b_{12} & \cdots &b_{1p}\\
b_{21} &b_{22} & \cdots &b_{2p}\\
\vdots & \vdots & \ddots & \vdots\\
b_{n1} &b_{n2} & \cdots & b_{np}\\
\end{pmatrix} = \begin{pmatrix} 
a_{11}\cdot b_{11} + a_{12} \cdot b_{21} + \cdots + a_{1n}\cdot b_{n1} & \sum_{k = 1}^n a_{1k}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{1k}\cdot b_{kp}\\
a_{21}\cdot b_{11} + a_{22} \cdot b_{21} + \cdots + a_{2n}\cdot b_{n1} & \sum_{k = 1}^n a_{2k}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{2k}\cdot b_{kp}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1}\cdot b_{11} + a_{m2} \cdot b_{21} + \cdots + a_{mn}\cdot b_{n1} & \sum_{k = 1}^n a_{mk}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{mk}\cdot b_{kp}
\end{pmatrix}\end{array}$$

Dadas dos matrices, la primera con el mismo número de columnas que filas tiene la segunda, podemos multiplicarlas del siguiente modo:

In [61]:
# Definiendo las matrices
A = [[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]]

In [63]:
# Multiplicación de ambas matrices

if len(A[0])==len(B):
    C = []
    for i in range(len(A)):
        C.append([])
        for j in range(len(B[j])):
            elemento = 0
            for k in range(len(B)):
                elemento = elemento + A[i][k]*B[k][j]
            C[i].append(elemento)
else:
    print("No se puede multiplicar ambas matrices")
C

[[1, 0, 7], [-1, -3, -4], [1, 2, 3]]

El resultado de multiplicar las matrices $A$ y $B$ ha sido

$$\begin{array}{lll} A\cdot B &=& 
\begin{pmatrix}
1 & 0 & -3 & 2\\
2 & 0 & 1 & 1\\
-1 & 0 & -1 & 0
\end{pmatrix}\cdot\begin{pmatrix}
-1 & -2 & 0\\
-2 & 3 & 0\\
0 & 0 & -3\\
1 & 1 & -1
\end{pmatrix}\\ &=& \begin{pmatrix}
1\cdot (-1) + 0\cdot (-2) -3\cdot 0 + 2\cdot 1 & 1\cdot (-2) + 0\cdot 3 -3\cdot 0 + 2\cdot 1 & 1\cdot 0 + 0\cdot 0 -3\cdot (-3) + 2\cdot (-1)\\
2\cdot (-1) + 0\cdot (-2) + 1\cdot 0 + 1\cdot 1  & 2\cdot (-2) + 0\cdot 3 + 1\cdot 0 + 1\cdot 1 & 2\cdot 0 + 0\cdot 0 + 1\cdot (-3) + 1\cdot (-1)\\
-1\cdot (-1) + 0\cdot (-2) -1\cdot 0 + 0\cdot 1  & -1\cdot (-2) + 0\cdot 3 -1\cdot 0 + 0\cdot 1 & -1\cdot 0 + 0\cdot 0 -1\cdot (-3) + 0\cdot (-1)
\end{pmatrix}\\ &=& \begin{pmatrix}
1 & 0 & 7\\
-1 & -3 & -4\\
1 & 2 & 3
\end{pmatrix}
\end{array}$$

**Ejemplo**
- El usuario debe ingresar los elementos de una matriz

In [68]:
m = int(input("Ingrese el número de filas : "))
n = int(input("Ingrese el número de columnas : "))

M = []
for i in range(m):
    M.append([])
    for j in range(n):
        print("fila {} columna {}".format(i+1,j+1))
        M[i].append(int(input("")))
M

Ingrese el número de filas : 4
Ingrese el número de columnas : 2
fila 1 columna 1
2
fila 1 columna 2
1
fila 2 columna 1
4
fila 2 columna 2
7
fila 3 columna 1
4
fila 3 columna 2
6
fila 4 columna 1
4
fila 4 columna 2
8


[[2, 1], [4, 7], [4, 6], [4, 8]]

In [2]:
# Matriz 2x2, con elementos ingresados por el usuario.
A = []
for i in range(2):
    A.append([])
    for j in range(2):
        A[i].append(float(input("Introduce el elemento ({},{}): ".format(i+1, j+1))))

for i in range(2):
    for j in range(2):
        print(A[i][j], end = "  " if A[i][j] >= 0 else " ")
    print("")

Introduce el elemento (1,1): 1
Introduce el elemento (1,2): 6
Introduce el elemento (2,1): 2
Introduce el elemento (2,2): 9
1.0  6.0  
2.0  9.0  


**Ejercicio**

- Vamos a sumar dos matrices con listas. Ambas matrices serán proporcionadas por el usuario, así como la dimensión de las matrices.

In [8]:
n = int(input("Ingrese el numero de filas : "))
m = int(input("Ingrese el numero de columnas : "))

# Primera matriz
M1 = []
for i in range(n):
    M1.append([])
    for j in range(m):
        print("Matriz A, posición {} , {}".format(1+i,1+j))
        M1[i].append(float(input("Ingrese elemento : ")))

# Segunda matriz
M2 = []
for i in range(n):
    M2.append([])
    for j in range(m):
        print("Matriz B, posición {} , {}".format(1+i,1+j))
        M2[i].append(float(input("Ingrese elemento : ")))

# Sumando ambas matrices
S = []
for i in range(n):
    S.append([])
    for j in range(m):
        S[i].append(M1[i][j] + M2[i][j])
S

Ingrese el numero de filas : 2
Ingrese el numero de columnas : 3
Matriz A, posición 1 , 1
Ingrese elemento : 1
Matriz A, posición 1 , 2
Ingrese elemento : 2
Matriz A, posición 1 , 3
Ingrese elemento : 3
Matriz A, posición 2 , 1
Ingrese elemento : 4
Matriz A, posición 2 , 2
Ingrese elemento : 5
Matriz A, posición 2 , 3
Ingrese elemento : 6
Matriz B, posición 1 , 1
Ingrese elemento : 0
Matriz B, posición 1 , 2
Ingrese elemento : 0
Matriz B, posición 1 , 3
Ingrese elemento : 0
Matriz B, posición 2 , 1
Ingrese elemento : 1
Matriz B, posición 2 , 2
Ingrese elemento : 1
Matriz B, posición 2 , 3
Ingrese elemento : 1


[[1.0, 2.0, 3.0], [5.0, 6.0, 7.0]]

**Ejercicio**

- Vamos a calcular el producto de dos matrices con listas. Ambas matrices serán dadas por el usuario así como las dimensiones de ambas.

In [13]:
n = int(input("Ingrese el numero de filas de A : "))
m = int(input("Ingrese el numero de columnas A : "))
p = int(input("Ingrese el número de columnas de B : "))

# Primera matriz
M1 = []
for i in range(n):
    M1.append([])
    for j in range(m):
        print("Matriz A, posición ({},{})".format(1+i,1+j))
        M1[i].append(float(input("Ingrese elemento : ")))

# Segunda matriz
M2 = []
for i in range(m):
    M2.append([])
    for j in range(p):
        print("Matriz B, posición ({},{})".format(1+i,1+j))
        M2[i].append(float(input("Ingrese elemento : ")))

# Multiplicando ambas matrices
P = []
for i in range(n):
    P.append([])
    for j in range(p):
        elemento = 0
        for k in range(n):
            elemento = elemento + M1[i][k]*M2[k][j]
    P[i].append(elemento)
P

Ingrese el numero de filas de M1 : 2
Ingrese el numero de columnas M1 : 3
Ingrese el número de columnas de M2 : 1
Matriz A, posición (1,1)
Ingrese elemento : 12
Matriz A, posición (1,2)
Ingrese elemento : 1
Matriz A, posición (1,3)
Ingrese elemento : 2
Matriz A, posición (2,1)
Ingrese elemento : 3
Matriz A, posición (2,2)
Ingrese elemento : 4
Matriz A, posición (2,3)
Ingrese elemento : 5
Matriz B, posición (1,1)
Ingrese elemento : 2
Matriz B, posición (2,1)
Ingrese elemento : 1
Matriz B, posición (3,1)
Ingrese elemento : 3


[[25.0], [10.0]]

In [15]:
n = int(input("Número de filas de la matriz A: "))
m = int(input("Número de columnas de la matriz A: "))
p = int(input("Número de columnas de la matriz B: "))

A = []
print("\n=== Matriz A ===")
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}) ".format(i+1,j+1))))

B = []
print("\n=== Matriz B ===")
for i in range(m):
    B.append([])
    for j in range(p):
        B[i].append(float(input("Introduce el elemento ({},{}) ".format(i+1,j+1))))

C = []
for i in range(n):
    C.append([])
    for j in range(p):
        elemento = 0
        for k in range(m):
            elemento += A[i][k] * B[k][j]
    C[i].append(elemento)

print("\n=== Matriz A · B ===")
for i in range(n):
    for j in range(p):
        print(C[i][j], end = "  " if C[i][j] >= 0 else " ")
  
    print("")

Número de filas de la matriz A: 3
Número de columnas de la matriz A: 1
Número de columnas de la matriz B: 1

=== Matriz A ===
Introduce el elemento (1,1) 1
Introduce el elemento (2,1) 2
Introduce el elemento (3,1) 3

=== Matriz B ===
Introduce el elemento (1,1) 2

=== Matriz A · B ===
2.0  
4.0  
6.0  


## Matrices con `numpy`

Existe una forma más sencilla de trabajar con matrices y es gracias a la librería `numpy`. Para importarla, simplemente hay que ejecutar la siguiente línea de código.

In [16]:
import numpy as np

Para crear una matriz vacía, usamos el método `.empty()`, al que le indicamos por parámetro las dimensiones

In [17]:
A = np.empty((2,3)) # 2 filas y 3 columnas
A

array([[0., 0., 0.],
       [0., 0., 0.]])

Para crear una matriz vacía con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.empty_like()`, al que le indicamos por parámetro la matriz existente

In [22]:
B = np.empty_like(A)
B

array([[0., 0., 0.],
       [0., 0., 0.]])

Para crear una matriz nula, usamos el método `.zeros()`, al que le indicamos por parámetro las dimensiones

In [23]:
C = np.zeros((3,5))
print(C)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Para crear una matriz de ceros con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.zeros_like()`, al que le indicamos por parámetro la matriz existente

In [24]:
D = np.zeros_like(C)
D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Para crear una matriz de unos, usamos el método `.ones()`, al que le indicamos por parámetro las dimensiones

In [26]:
E = np.ones((2,5))
E

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Para crear una matriz de unos con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.ones_like()`, al que le indicamos por parámetro la matriz existente

In [28]:
F = np.ones_like(A) # A es una matrz de 2x3
F

array([[1., 1., 1.],
       [1., 1., 1.]])

Podemos crear matrices de numpy a partir de listas con el método `.matrix()`

In [29]:
M = np.matrix([[1,0,2],[2,-3,1]])
M

matrix([[ 1,  0,  2],
        [ 2, -3,  1]])

In [30]:
print(M)

[[ 1  0  2]
 [ 2 -3  1]]


Para saber las dimensiones de una matriz, podemos utilizar el método `.shape`


In [31]:
M.shape

(2, 3)

Ahora es más sencillo sumar matrices, pues solamente necesitamos la función `+`

In [32]:
A = np.matrix([[1, 0, -3], [2, 0, 1], [-1, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3]])
matrixSum = A + B
matrixSum

matrix([[ 0, -2, -3],
        [ 0,  3,  1],
        [-1, -1, -3]])

También es más sencillo hacer el producto matricial $A\cdot B$ con el método `.dot()`

In [33]:
A = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]])

matrixProd = A.dot(B)
matrixProd

matrix([[ 1,  0,  7],
        [-1, -3, -4],
        [ 1,  2,  3]])

Gracias a `numpy`, también es mucho más sencillo mostrar una matriz en forma de tabla, pues nos basta con hacer uso de la función `print()`:

In [38]:
print(matrixSum)

[[ 0 -2 -3]
 [ 0  3  1]
 [-1 -1 -3]]


In [39]:
print(matrixProd)

[[ 1  0  7]
 [-1 -3 -4]
 [ 1  2  3]]


**Ejercicio**

- Vamos a introducir manualmente una matriz con `numpy` donde las dimensiones son proporcionadas por el usuario.

In [49]:
# Previamente de tiene que llamar al módulo numpy
n = int(input("Número de fllas : "))
m = int(input("Número de columnas : "))

A = np.empty((n,m))
print(A)
for i in range(n):
    for j in range(m):
        A[i,j] = float(input("Ingrese elemento ({},{}) : ".format(i+1,j+1)))

A

Número de fllas : 2
Número de columnas : 3
[[1. 2. 3.]
 [4. 5. 6.]]
Ingrese elemento (1,1) : 1
Ingrese elemento (1,2) : 6
Ingrese elemento (1,3) : 9
Ingrese elemento (2,1) : 2
Ingrese elemento (2,2) : 3
Ingrese elemento (2,3) : 0


array([[1., 6., 9.],
       [2., 3., 0.]])

**Ejercicio**

- Vamos a sumar dos matrices con `numpy`. Ambas matrices las proporcionará el usuario, así como sus dimensiones.

In [54]:
# Previamente de tiene que llamar al módulo numpy
n = int(input("Número de fllas : "))
m = int(input("Número de columnas : "))

A = np.empty((n,m))
B = np.empty((n,m))

print("Matriz A")
for i in range(n):
    for j in range(m):
        A[i,j] = float(input("Ingrese elemento ({},{}) : ".format(i+1,j+1)))

print("Matriz B")
for i in range(n):
    for j in range(m):
        B[i,j] = float(input("Ingrese elemento ({},{}) : ".format(i+1,j+1)))

S = np.empty((n,m))     
# Sumando ambas matrices
for i in range(n):
    for j in range(m):
        S[i,j] = A[i,j] + B[i,j]
print("*"*40)
print("La suma es : ")
print(S)
print("***")
print(A+B)

Número de fllas : 2
Número de columnas : 3
Matriz A
Ingrese elemento (1,1) : 1
Ingrese elemento (1,2) : 2
Ingrese elemento (1,3) : 3
Ingrese elemento (2,1) : 4
Ingrese elemento (2,2) : 5
Ingrese elemento (2,3) : 6
Matriz B
Ingrese elemento (1,1) : 7
Ingrese elemento (1,2) : 6
Ingrese elemento (1,3) : 5
Ingrese elemento (2,1) : 4
Ingrese elemento (2,2) : 3
Ingrese elemento (2,3) : 2
****************************************
La suma es : 
[[8. 8. 8.]
 [8. 8. 8.]]
[[8. 8. 8.]
 [8. 8. 8.]]


**Ejercicio**

- Vamos a multiplicar dos matrices con `numpy`. Ambas matrices serán proporcionadas por el usuario, así como la dimensión de ambas.

In [55]:
n = int(input("Ingrese el número de filas de A : "))
m = int(input("Ingrese el número de columnas de A o número de filas de B : "))
p = int(input("Ingrese el número de columnas de B"))

A = np.empty((n,m))
B = np.empty((m,p))

print("*"*30)
print("Matriz A")
for i in range(n):
    for j in range(m):
        A[i,j] = float(input("Matriz A posicion ({},{}) : ".format(i+1,j+1)))
print("*"*30)
print("Matriz A")
for i in range(m):
    for j in range(p):
        B[i,j] = float(input("Matriz B posicion ({},{}) : ".format(i+1,j+1)))
print("*"*30)        
print("La multiplicación de A . B es : ")
print(A.dot(B))

Ingrese el número de filas de A : 2
Ingrese el número de columnas de A o número de filas de B : 3
Ingrese el número de columnas de B1
******************************
Matriz A
Matriz A posicion (1,1) : 1
Matriz A posicion (1,2) : 2
Matriz A posicion (1,3) : 3
Matriz A posicion (2,1) : 4
Matriz A posicion (2,2) : 5
Matriz A posicion (2,3) : 6
******************************
Matriz A
Matriz B posicion (1,1) : 10
Matriz B posicion (2,1) : 20
Matriz B posicion (3,1) : 30
******************************
La multiplicación de A . B es : 
[[140.]
 [320.]]
